### ISSUE TITLE
setItemCount(3);时候数据不显示

### ISSUE THREAD

**Issue by CaiJinFu** [chenxinfei/LocateCenterHorizontalView#3]
setItemCount方法只能大于或等于5数据才会显示 现在想要的效果是文字全部显示完全 但是数字过多的时候就显示不出来了 在adapter里的布局 textview去掉了  android:singleLine="true" 还是显示不完全那个字？请问怎么解决

**Comment by chenxinfei** [comment]
你好，刚看见，不好意思，修改LocateCenterHorizontalView类中onCreateViewHolder方法的params.height的高度可以解决

**Comment by chenxinfei** [comment]
你好，刚看见，不好意思，修改LocateCenterHorizontalView类中onCreateViewHolder方法的params.height的高度可以解决
